# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.intercurrent_event import IntercurrentEvent  # noqa: E501

class TestIntercurrentEvent(unittest.TestCase):
    """IntercurrentEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntercurrentEvent:
        """Test IntercurrentEvent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntercurrentEvent`
        """
        model = IntercurrentEvent()  # noqa: E501
        if include_optional:
            return IntercurrentEvent(
                id = '',
                name = '',
                description = '',
                label = '',
                text = '',
                notes = [
                    ''
                    ],
                dictionary = '',
                strategy = '',
                instance_type = ''
            )
        else:
            return IntercurrentEvent(
                id = '',
                name = '',
                description = '',
                label = '',
                text = '',
                strategy = '',
        )
        """

    def testIntercurrentEvent(self):
        """Test IntercurrentEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
