/**
 * USDM to OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* NCI C-Code: C69282 Definition: The amount of time elapsed during the administration of an agent. Preferred Term: Administration Duration
*/
export class AdministrationDuration {
    'id': string;
    'description': string;
    'durationWillVary': string;
    'reasonDurationWillVary': string;
    'quantity'?: string;
    'instanceType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "durationWillVary",
            "baseName": "durationWillVary",
            "type": "string",
            "format": ""
        },
        {
            "name": "reasonDurationWillVary",
            "baseName": "reasonDurationWillVary",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AdministrationDuration.attributeTypeMap;
    }

    public constructor() {
    }
}
