/**
 * USDM to OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* NCI C-Code: C25409 Definition: The act of dispensing, applying, or tendering a product, agent, or therapy. Preferred Term: Administration
*/
export class Administration {
    'id': string;
    'name': string;
    'description': string;
    'label': string;
    'administrableProduct'?: string;
    'route'?: string;
    'dose'?: string;
    'frequency'?: string;
    'notes'?: Array<string>;
    'duration': string;
    'medicalDevice'?: string;
    'instanceType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "administrableProduct",
            "baseName": "administrableProduct",
            "type": "string",
            "format": ""
        },
        {
            "name": "route",
            "baseName": "route",
            "type": "string",
            "format": ""
        },
        {
            "name": "dose",
            "baseName": "dose",
            "type": "string",
            "format": ""
        },
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": ""
        },
        {
            "name": "medicalDevice",
            "baseName": "medicalDevice",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Administration.attributeTypeMap;
    }

    public constructor() {
    }
}
