/**
 * USDM to OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* NCI C-Code: CNEW Definition: A citation pointing to the location of specific content within a document. Preferred Term: Document Content Reference
*/
export class DocumentContentReference {
    'id': string;
    'sectionNumber': string;
    'sectionTitle': string;
    'appliesTo': string;
    'instanceType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sectionNumber",
            "baseName": "sectionNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "sectionTitle",
            "baseName": "sectionTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "appliesTo",
            "baseName": "appliesTo",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentContentReference.attributeTypeMap;
    }

    public constructor() {
    }
}
