/**
 * USDM to OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* NCI C-Code: CNEW Definition: Any physical or virtual contact between two or more parties involved in a study, at which an assessment or activity takes place. Preferred Term: Study Encounter
*/
export class Encounter {
    'id': string;
    'name': string;
    'description': string;
    'label': string;
    'environmentalSettings'?: Array<string>;
    'contactModes'?: Array<string>;
    'type': string;
    'notes'?: Array<string>;
    'transitionEndRule'?: string;
    'next'?: string;
    'transitionStartRule'?: string;
    'scheduledAt'?: string;
    'previous'?: string;
    'instanceType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "environmentalSettings",
            "baseName": "environmentalSettings",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "contactModes",
            "baseName": "contactModes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "transitionEndRule",
            "baseName": "transitionEndRule",
            "type": "string",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": ""
        },
        {
            "name": "transitionStartRule",
            "baseName": "transitionStartRule",
            "type": "string",
            "format": ""
        },
        {
            "name": "scheduledAt",
            "baseName": "scheduledAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Encounter.attributeTypeMap;
    }

    public constructor() {
    }
}
