/**
 * USDM to OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* NCI C-Code: C142728 Definition: The population within the general population to which the study results can be generalized. Preferred Term: Study Design Population
*/
export class StudyDesignPopulation {
    'id': string;
    'name': string;
    'description': string;
    'label': string;
    'includesHealthySubjects': string;
    'plannedSex'?: string;
    'notes'?: Array<string>;
    'criteria'?: Array<string>;
    'plannedAge'?: string;
    'plannedEnrollmentNumber'?: string;
    'plannedCompletionNumber'?: string;
    'cohorts'?: Array<string>;
    'instanceType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "includesHealthySubjects",
            "baseName": "includesHealthySubjects",
            "type": "string",
            "format": ""
        },
        {
            "name": "plannedSex",
            "baseName": "plannedSex",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "criteria",
            "baseName": "criteria",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "plannedAge",
            "baseName": "plannedAge",
            "type": "string",
            "format": ""
        },
        {
            "name": "plannedEnrollmentNumber",
            "baseName": "plannedEnrollmentNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "plannedCompletionNumber",
            "baseName": "plannedCompletionNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "cohorts",
            "baseName": "cohorts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StudyDesignPopulation.attributeTypeMap;
    }

    public constructor() {
    }
}
