# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist

class GovernanceDate(BaseModel):
    """
    NCI C-Code: C207595 Definition: Any of the dates associated with event milestones within a clinical study's oversight and management framework. Preferred Term: Study Governance Date  # noqa: E501
    """
    id: StrictStr = Field(...)
    name: StrictStr = Field(...)
    description: StrictStr = Field(...)
    label: StrictStr = Field(...)
    date_value: StrictStr = Field(default=..., alias="dateValue")
    type: StrictStr = Field(...)
    geographic_scopes: conlist(StrictStr) = Field(default=..., alias="geographicScopes")
    instance_type: Optional[StrictStr] = Field(default=None, alias="instanceType")
    __properties = ["id", "name", "description", "label", "dateValue", "type", "geographicScopes", "instanceType"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GovernanceDate:
        """Create an instance of GovernanceDate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GovernanceDate:
        """Create an instance of GovernanceDate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GovernanceDate.parse_obj(obj)

        _obj = GovernanceDate.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "label": obj.get("label"),
            "date_value": obj.get("dateValue"),
            "type": obj.get("type"),
            "geographic_scopes": obj.get("geographicScopes"),
            "instance_type": obj.get("instanceType")
        })
        return _obj


