# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist

class StudyIntervention(BaseModel):
    """
    NCI C-Code: C207649 Definition: Any agent, device, or procedure being tested or used as a reference or comparator in the conduct of a clinical trial. Preferred Term: Study Intervention  # noqa: E501
    """
    id: StrictStr = Field(...)
    description: StrictStr = Field(...)
    name: StrictStr = Field(...)
    label: StrictStr = Field(...)
    administrations: Optional[conlist(StrictStr)] = None
    type: StrictStr = Field(...)
    role: StrictStr = Field(...)
    codes: Optional[conlist(StrictStr)] = None
    notes: Optional[conlist(StrictStr)] = None
    minimum_response_duration: Optional[StrictStr] = Field(default=None, alias="minimumResponseDuration")
    instance_type: Optional[StrictStr] = Field(default=None, alias="instanceType")
    __properties = ["id", "description", "name", "label", "administrations", "type", "role", "codes", "notes", "minimumResponseDuration", "instanceType"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StudyIntervention:
        """Create an instance of StudyIntervention from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StudyIntervention:
        """Create an instance of StudyIntervention from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StudyIntervention.parse_obj(obj)

        _obj = StudyIntervention.parse_obj({
            "id": obj.get("id"),
            "description": obj.get("description"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "administrations": obj.get("administrations"),
            "type": obj.get("type"),
            "role": obj.get("role"),
            "codes": obj.get("codes"),
            "notes": obj.get("notes"),
            "minimum_response_duration": obj.get("minimumResponseDuration"),
            "instance_type": obj.get("instanceType")
        })
        return _obj


