# coding: utf-8

"""
    DDF USDM API

    A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.

    The version of the OpenAPI document: 3.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.study_amendment_reason import StudyAmendmentReason  # noqa: E501

class TestStudyAmendmentReason(unittest.TestCase):
    """StudyAmendmentReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudyAmendmentReason:
        """Test StudyAmendmentReason
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudyAmendmentReason`
        """
        model = StudyAmendmentReason()  # noqa: E501
        if include_optional:
            return StudyAmendmentReason(
                id = '0',
                code = openapi_client.models.code.Code(
                    id = '0', 
                    code = '', 
                    code_system = '', 
                    code_system_version = '', 
                    decode = '', 
                    instance_type = 'Code', ),
                other_reason = '',
                instance_type = 'StudyAmendmentReason'
            )
        else:
            return StudyAmendmentReason(
                id = '0',
                code = openapi_client.models.code.Code(
                    id = '0', 
                    code = '', 
                    code_system = '', 
                    code_system_version = '', 
                    decode = '', 
                    instance_type = 'Code', ),
                instance_type = 'StudyAmendmentReason',
        )
        """

    def testStudyAmendmentReason(self):
        """Test StudyAmendmentReason"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
