# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.administrable_product import AdministrableProduct

class TestAdministrableProduct(unittest.TestCase):
    """AdministrableProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdministrableProduct:
        """Test AdministrableProduct
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdministrableProduct`
        """
        model = AdministrableProduct()
        if include_optional:
            return AdministrableProduct(
                id = '',
                name = '',
                description = '',
                label = '',
                product_designation = '',
                administrable_dose_form = '',
                notes = [
                    ''
                    ],
                pharmacologic_class = '',
                identifiers = [
                    ''
                    ],
                properties = [
                    ''
                    ],
                sourcing = '',
                ingredients = [
                    ''
                    ],
                instance_type = ''
            )
        else:
            return AdministrableProduct(
                id = '',
                name = '',
                description = '',
                label = '',
                product_designation = '',
                administrable_dose_form = '',
        )
        """

    def testAdministrableProduct(self):
        """Test AdministrableProduct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
