# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scheduled_instance import ScheduledInstance

class TestScheduledInstance(unittest.TestCase):
    """ScheduledInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduledInstance:
        """Test ScheduledInstance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduledInstance`
        """
        model = ScheduledInstance()
        if include_optional:
            return ScheduledInstance(
                id = '',
                name = '',
                description = '',
                label = '',
                default_condition = '',
                epoch = ''
            )
        else:
            return ScheduledInstance(
                id = '',
                name = '',
                description = '',
                label = '',
        )
        """

    def testScheduledInstance(self):
        """Test ScheduledInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
