# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schedule_timeline import ScheduleTimeline

class TestScheduleTimeline(unittest.TestCase):
    """ScheduleTimeline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleTimeline:
        """Test ScheduleTimeline
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleTimeline`
        """
        model = ScheduleTimeline()
        if include_optional:
            return ScheduleTimeline(
                id = '',
                name = '',
                description = '',
                label = '',
                entry_condition = '',
                main_timeline = '',
                instances = [
                    ''
                    ],
                entry = '',
                exits = [
                    ''
                    ],
                timings = [
                    ''
                    ],
                instance_type = ''
            )
        else:
            return ScheduleTimeline(
                id = '',
                name = '',
                description = '',
                label = '',
                entry_condition = '',
                main_timeline = '',
                entry = '',
        )
        """

    def testScheduleTimeline(self):
        """Test ScheduleTimeline"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
