# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.study_cohort import StudyCohort

class TestStudyCohort(unittest.TestCase):
    """StudyCohort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudyCohort:
        """Test StudyCohort
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudyCohort`
        """
        model = StudyCohort()
        if include_optional:
            return StudyCohort(
                id = '',
                name = '',
                description = '',
                label = '',
                includes_healthy_subjects = '',
                planned_sex = '',
                notes = [
                    ''
                    ],
                criteria = [
                    ''
                    ],
                planned_age = '',
                planned_enrollment_number = '',
                planned_completion_number = '',
                characteristics = [
                    ''
                    ],
                instance_type = ''
            )
        else:
            return StudyCohort(
                id = '',
                name = '',
                description = '',
                label = '',
                includes_healthy_subjects = '',
        )
        """

    def testStudyCohort(self):
        """Test StudyCohort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
