# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.eligibility_criterion import EligibilityCriterion

class TestEligibilityCriterion(unittest.TestCase):
    """EligibilityCriterion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EligibilityCriterion:
        """Test EligibilityCriterion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EligibilityCriterion`
        """
        model = EligibilityCriterion()
        if include_optional:
            return EligibilityCriterion(
                id = '',
                name = '',
                description = '',
                label = '',
                text = '',
                notes = [
                    ''
                    ],
                dictionary = '',
                identifier = '',
                category = '',
                next = '',
                previous = '',
                instance_type = ''
            )
        else:
            return EligibilityCriterion(
                id = '',
                name = '',
                description = '',
                label = '',
                text = '',
                identifier = '',
                category = '',
        )
        """

    def testEligibilityCriterion(self):
        """Test EligibilityCriterion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
