# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.administration_duration import AdministrationDuration

class TestAdministrationDuration(unittest.TestCase):
    """AdministrationDuration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdministrationDuration:
        """Test AdministrationDuration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdministrationDuration`
        """
        model = AdministrationDuration()
        if include_optional:
            return AdministrationDuration(
                id = '',
                description = '',
                duration_will_vary = '',
                reason_duration_will_vary = '',
                quantity = '',
                instance_type = ''
            )
        else:
            return AdministrationDuration(
                id = '',
                description = '',
                duration_will_vary = '',
                reason_duration_will_vary = '',
        )
        """

    def testAdministrationDuration(self):
        """Test AdministrationDuration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
