# coding: utf-8

"""
    USDM to OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.governance_date import GovernanceDate

class TestGovernanceDate(unittest.TestCase):
    """GovernanceDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GovernanceDate:
        """Test GovernanceDate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GovernanceDate`
        """
        model = GovernanceDate()
        if include_optional:
            return GovernanceDate(
                id = '',
                name = '',
                description = '',
                label = '',
                date_value = '',
                type = '',
                geographic_scopes = [
                    ''
                    ],
                instance_type = ''
            )
        else:
            return GovernanceDate(
                id = '',
                name = '',
                description = '',
                label = '',
                date_value = '',
                type = '',
                geographic_scopes = [
                    ''
                    ],
        )
        """

    def testGovernanceDate(self):
        """Test GovernanceDate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
