# coding: utf-8

"""
    DDF USDM API

    A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.

    The version of the OpenAPI document: 3.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scheduled_activity_instance import ScheduledActivityInstance

class TestScheduledActivityInstance(unittest.TestCase):
    """ScheduledActivityInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduledActivityInstance:
        """Test ScheduledActivityInstance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduledActivityInstance`
        """
        model = ScheduledActivityInstance()
        if include_optional:
            return ScheduledActivityInstance(
                id = '0',
                name = '0',
                label = '',
                description = '',
                default_condition_id = '',
                epoch_id = '',
                instance_type = 'ScheduledActivityInstance',
                timeline_id = '',
                timeline_exit_id = '',
                activity_ids = [
                    ''
                    ],
                encounter_id = ''
            )
        else:
            return ScheduledActivityInstance(
                id = '0',
                name = '0',
                instance_type = 'ScheduledActivityInstance',
        )
        """

    def testScheduledActivityInstance(self):
        """Test ScheduledActivityInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
