# coding: utf-8

"""
    DDF USDM API

    A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.

    The version of the OpenAPI document: 3.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.study_element_output import StudyElementOutput

class TestStudyElementOutput(unittest.TestCase):
    """StudyElementOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StudyElementOutput:
        """Test StudyElementOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StudyElementOutput`
        """
        model = StudyElementOutput()
        if include_optional:
            return StudyElementOutput(
                id = '0',
                name = '0',
                label = '',
                description = '',
                transition_start_rule = openapi_client.models.transition_rule.TransitionRule(
                    id = '0', 
                    name = '0', 
                    label = '', 
                    description = '', 
                    text = '', 
                    instance_type = 'TransitionRule', ),
                transition_end_rule = openapi_client.models.transition_rule.TransitionRule(
                    id = '0', 
                    name = '0', 
                    label = '', 
                    description = '', 
                    text = '', 
                    instance_type = 'TransitionRule', ),
                study_intervention_ids = [
                    ''
                    ],
                notes = [
                    openapi_client.models.comment_annotation.CommentAnnotation(
                        id = '0', 
                        text = '', 
                        codes = [
                            openapi_client.models.code.Code(
                                id = '0', 
                                code = '', 
                                code_system = '', 
                                code_system_version = '', 
                                decode = '', 
                                instance_type = 'Code', )
                            ], 
                        instance_type = 'CommentAnnotation', )
                    ],
                instance_type = 'StudyElement'
            )
        else:
            return StudyElementOutput(
                id = '0',
                name = '0',
                instance_type = 'StudyElement',
        )
        """

    def testStudyElementOutput(self):
        """Test StudyElementOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
