/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentAnnotation } from '../models/CommentAnnotation';

export class AbbreviationOutput {
    'id': string;
    'abbreviatedText': string;
    'expandedText': string;
    'notes'?: Array<CommentAnnotation>;
    'instanceType': AbbreviationOutputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "abbreviatedText",
            "baseName": "abbreviatedText",
            "type": "string",
            "format": ""
        },
        {
            "name": "expandedText",
            "baseName": "expandedText",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<CommentAnnotation>",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "AbbreviationOutputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AbbreviationOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AbbreviationOutputInstanceTypeEnum {
    Abbreviation = 'Abbreviation'
}

