/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuantityOutput } from '../models/QuantityOutput';


export class AdministrationDurationOutput {
    'id': string;
    'quantity'?: QuantityOutput | null;
    'description': string;
    'durationWillVary': boolean;
    'reasonDurationWillVary': string;
    'instanceType': AdministrationDurationOutputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "QuantityOutput",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "durationWillVary",
            "baseName": "durationWillVary",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reasonDurationWillVary",
            "baseName": "reasonDurationWillVary",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "AdministrationDurationOutputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AdministrationDurationOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AdministrationDurationOutputInstanceTypeEnum {
    AdministrationDuration = 'AdministrationDuration'
}

