/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class ConditionAssignment {
    'id': string;
    'condition': string;
    'conditionTargetId': string;
    'instanceType': ConditionAssignmentInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "string",
            "format": ""
        },
        {
            "name": "conditionTargetId",
            "baseName": "conditionTargetId",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "ConditionAssignmentInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConditionAssignment.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ConditionAssignmentInstanceTypeEnum {
    ConditionAssignment = 'ConditionAssignment'
}

