/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentAnnotation } from '../models/CommentAnnotation';
import { IntercurrentEventOutput } from '../models/IntercurrentEventOutput';


export class EstimandOutput {
    'id': string;
    'name': string;
    'label'?: string | null;
    'description'?: string | null;
    'populationSummary': string;
    'analysisPopulationId': string;
    'interventionIds': Array<string>;
    'variableOfInterestId': string;
    'intercurrentEvents': Array<IntercurrentEventOutput>;
    'notes'?: Array<CommentAnnotation>;
    'instanceType': EstimandOutputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "populationSummary",
            "baseName": "populationSummary",
            "type": "string",
            "format": ""
        },
        {
            "name": "analysisPopulationId",
            "baseName": "analysisPopulationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "interventionIds",
            "baseName": "interventionIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "variableOfInterestId",
            "baseName": "variableOfInterestId",
            "type": "string",
            "format": ""
        },
        {
            "name": "intercurrentEvents",
            "baseName": "intercurrentEvents",
            "type": "Array<IntercurrentEventOutput>",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<CommentAnnotation>",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "EstimandOutputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EstimandOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum EstimandOutputInstanceTypeEnum {
    Estimand = 'Estimand'
}

