/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AliasCode } from '../models/AliasCode';
import { Code } from '../models/Code';


export class GeographicScopeOutput {
    'id': string;
    'type': Code;
    'code'?: AliasCode | null;
    'instanceType': GeographicScopeOutputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Code",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "AliasCode",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "GeographicScopeOutputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GeographicScopeOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GeographicScopeOutputInstanceTypeEnum {
    GeographicScope = 'GeographicScope'
}

