/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Code } from '../models/Code';
import { SubstanceInput } from '../models/SubstanceInput';


export class IngredientInput {
    'id': string;
    'role': Code;
    'substance': SubstanceInput;
    'instanceType': IngredientInputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "Code",
            "format": ""
        },
        {
            "name": "substance",
            "baseName": "substance",
            "type": "SubstanceInput",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "IngredientInputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IngredientInput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum IngredientInputInstanceTypeEnum {
    Ingredient = 'Ingredient'
}

