/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from '../models/Address';
import { Code } from '../models/Code';
import { StudySite } from '../models/StudySite';


export class OrganizationInput {
    'id': string;
    'name': string;
    'label'?: string | null;
    'type': Code;
    'identifierScheme': string;
    'identifier': string;
    'legalAddress'?: Address | null;
    'managedSites'?: Array<StudySite>;
    'instanceType': OrganizationInputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Code",
            "format": ""
        },
        {
            "name": "identifierScheme",
            "baseName": "identifierScheme",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "legalAddress",
            "baseName": "legalAddress",
            "type": "Address",
            "format": ""
        },
        {
            "name": "managedSites",
            "baseName": "managedSites",
            "type": "Array<StudySite>",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "OrganizationInputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationInput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum OrganizationInputInstanceTypeEnum {
    Organization = 'Organization'
}

