/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AliasCode } from '../models/AliasCode';


export class RangeOutput {
    'id': string;
    'minValue': number;
    'maxValue': number;
    'unit'?: AliasCode | null;
    'isApproximate': boolean;
    'instanceType': RangeOutputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "minValue",
            "baseName": "minValue",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxValue",
            "baseName": "maxValue",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "AliasCode",
            "format": ""
        },
        {
            "name": "isApproximate",
            "baseName": "isApproximate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "RangeOutputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RangeOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum RangeOutputInstanceTypeEnum {
    Range = 'Range'
}

