/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class ScheduledActivityInstance {
    'id': string;
    'name': string;
    'label'?: string | null;
    'description'?: string | null;
    'defaultConditionId'?: string | null;
    'epochId'?: string | null;
    'instanceType': ScheduledActivityInstanceInstanceTypeEnum;
    'timelineId'?: string | null;
    'timelineExitId'?: string | null;
    'activityIds'?: Array<string | null>;
    'encounterId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultConditionId",
            "baseName": "defaultConditionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "epochId",
            "baseName": "epochId",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "ScheduledActivityInstanceInstanceTypeEnum",
            "format": ""
        },
        {
            "name": "timelineId",
            "baseName": "timelineId",
            "type": "string",
            "format": ""
        },
        {
            "name": "timelineExitId",
            "baseName": "timelineExitId",
            "type": "string",
            "format": ""
        },
        {
            "name": "activityIds",
            "baseName": "activityIds",
            "type": "Array<string | null>",
            "format": ""
        },
        {
            "name": "encounterId",
            "baseName": "encounterId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScheduledActivityInstance.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ScheduledActivityInstanceInstanceTypeEnum {
    ScheduledActivityInstance = 'ScheduledActivityInstance'
}

