/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentAnnotation } from '../models/CommentAnnotation';
import { TransitionRule } from '../models/TransitionRule';


export class StudyElementInput {
    'id': string;
    'name': string;
    'label'?: string | null;
    'description'?: string | null;
    'transitionStartRule'?: TransitionRule | null;
    'transitionEndRule'?: TransitionRule | null;
    'studyInterventionIds'?: Array<string | null>;
    'notes'?: Array<CommentAnnotation>;
    'instanceType': StudyElementInputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "transitionStartRule",
            "baseName": "transitionStartRule",
            "type": "TransitionRule",
            "format": ""
        },
        {
            "name": "transitionEndRule",
            "baseName": "transitionEndRule",
            "type": "TransitionRule",
            "format": ""
        },
        {
            "name": "studyInterventionIds",
            "baseName": "studyInterventionIds",
            "type": "Array<string | null>",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<CommentAnnotation>",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "StudyElementInputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StudyElementInput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StudyElementInputInstanceTypeEnum {
    StudyElement = 'StudyElement'
}

