/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Code } from '../models/Code';
import { CommentAnnotation } from '../models/CommentAnnotation';


export class StudyArmOutput {
    'id': string;
    'name': string;
    'label'?: string | null;
    'description'?: string | null;
    'type': Code;
    'dataOriginDescription': string;
    'dataOriginType': Code;
    'populationIds'?: Array<string>;
    'notes'?: Array<CommentAnnotation>;
    'instanceType': StudyArmOutputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Code",
            "format": ""
        },
        {
            "name": "dataOriginDescription",
            "baseName": "dataOriginDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataOriginType",
            "baseName": "dataOriginType",
            "type": "Code",
            "format": ""
        },
        {
            "name": "populationIds",
            "baseName": "populationIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<CommentAnnotation>",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "StudyArmOutputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StudyArmOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StudyArmOutputInstanceTypeEnum {
    StudyArm = 'StudyArm'
}

