/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentAnnotation } from '../models/CommentAnnotation';
import { GeographicScopeInput } from '../models/GeographicScopeInput';
import { GovernanceDateInput } from '../models/GovernanceDateInput';
import { StudyAmendmentImpactInput } from '../models/StudyAmendmentImpactInput';
import { StudyAmendmentReason } from '../models/StudyAmendmentReason';
import { StudyChange } from '../models/StudyChange';
import { SubjectEnrollmentInput } from '../models/SubjectEnrollmentInput';


export class StudyAmendmentInput {
    'id': string;
    'number': string;
    'summary': string;
    'primaryReason': StudyAmendmentReason;
    'secondaryReasons'?: Array<StudyAmendmentReason>;
    'changes': Array<StudyChange>;
    'impacts'?: Array<StudyAmendmentImpactInput>;
    'geographicScopes': Array<GeographicScopeInput>;
    'enrollments'?: Array<SubjectEnrollmentInput>;
    'dateValues'?: Array<GovernanceDateInput>;
    'previousId'?: string | null;
    'notes'?: Array<CommentAnnotation>;
    'instanceType': StudyAmendmentInputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "primaryReason",
            "baseName": "primaryReason",
            "type": "StudyAmendmentReason",
            "format": ""
        },
        {
            "name": "secondaryReasons",
            "baseName": "secondaryReasons",
            "type": "Array<StudyAmendmentReason>",
            "format": ""
        },
        {
            "name": "changes",
            "baseName": "changes",
            "type": "Array<StudyChange>",
            "format": ""
        },
        {
            "name": "impacts",
            "baseName": "impacts",
            "type": "Array<StudyAmendmentImpactInput>",
            "format": ""
        },
        {
            "name": "geographicScopes",
            "baseName": "geographicScopes",
            "type": "Array<GeographicScopeInput>",
            "format": ""
        },
        {
            "name": "enrollments",
            "baseName": "enrollments",
            "type": "Array<SubjectEnrollmentInput>",
            "format": ""
        },
        {
            "name": "dateValues",
            "baseName": "dateValues",
            "type": "Array<GovernanceDateInput>",
            "format": ""
        },
        {
            "name": "previousId",
            "baseName": "previousId",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<CommentAnnotation>",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "StudyAmendmentInputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StudyAmendmentInput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StudyAmendmentInputInstanceTypeEnum {
    StudyAmendment = 'StudyAmendment'
}

