/**
 * DDF USDM API
 * A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.
 *
 * OpenAPI spec version: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Code } from '../models/Code';
import { CommentAnnotation } from '../models/CommentAnnotation';
import { GovernanceDateOutput } from '../models/GovernanceDateOutput';
import { NarrativeContent } from '../models/NarrativeContent';


export class StudyDefinitionDocumentVersionOutput {
    'id': string;
    'version': string;
    'status': Code;
    'dateValues'?: Array<GovernanceDateOutput>;
    'contents'?: Array<NarrativeContent>;
    'childIds'?: Array<string>;
    'notes'?: Array<CommentAnnotation>;
    'instanceType': StudyDefinitionDocumentVersionOutputInstanceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Code",
            "format": ""
        },
        {
            "name": "dateValues",
            "baseName": "dateValues",
            "type": "Array<GovernanceDateOutput>",
            "format": ""
        },
        {
            "name": "contents",
            "baseName": "contents",
            "type": "Array<NarrativeContent>",
            "format": ""
        },
        {
            "name": "childIds",
            "baseName": "childIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<CommentAnnotation>",
            "format": ""
        },
        {
            "name": "instanceType",
            "baseName": "instanceType",
            "type": "StudyDefinitionDocumentVersionOutputInstanceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StudyDefinitionDocumentVersionOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StudyDefinitionDocumentVersionOutputInstanceTypeEnum {
    StudyDefinitionDocumentVersion = 'StudyDefinitionDocumentVersion'
}

