# coding: utf-8

"""
    DDF USDM API

    A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.

    The version of the OpenAPI document: 3.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.code import Code
from typing import Optional, Set
from typing_extensions import Self

class AliasCode(BaseModel):
    """
    AliasCode
    """ # noqa: E501
    id: Annotated[str, Field(min_length=1, strict=True)]
    standard_code: Code = Field(alias="standardCode")
    standard_code_aliases: Optional[List[Code]] = Field(default=None, alias="standardCodeAliases")
    instance_type: StrictStr = Field(alias="instanceType")
    __properties: ClassVar[List[str]] = ["id", "standardCode", "standardCodeAliases", "instanceType"]

    @field_validator('instance_type')
    def instance_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['AliasCode']):
            raise ValueError("must be one of enum values ('AliasCode')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AliasCode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of standard_code
        if self.standard_code:
            _dict['standardCode'] = self.standard_code.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in standard_code_aliases (list)
        _items = []
        if self.standard_code_aliases:
            for _item_standard_code_aliases in self.standard_code_aliases:
                if _item_standard_code_aliases:
                    _items.append(_item_standard_code_aliases.to_dict())
            _dict['standardCodeAliases'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AliasCode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "standardCode": Code.from_dict(obj["standardCode"]) if obj.get("standardCode") is not None else None,
            "standardCodeAliases": [Code.from_dict(_item) for _item in obj["standardCodeAliases"]] if obj.get("standardCodeAliases") is not None else None,
            "instanceType": obj.get("instanceType")
        })
        return _obj


