# coding: utf-8

"""
    DDF USDM API

    A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.

    The version of the OpenAPI document: 3.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr, validator
from openapi_client.models.code import Code

class CommentAnnotation(BaseModel):
    """
    CommentAnnotation
    """
    id: constr(strict=True, min_length=1) = Field(...)
    text: StrictStr = Field(...)
    codes: Optional[conlist(Code)] = None
    instance_type: StrictStr = Field(default=..., alias="instanceType")
    __properties = ["id", "text", "codes", "instanceType"]

    @validator('instance_type')
    def instance_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('CommentAnnotation',):
            raise ValueError("must be one of enum values ('CommentAnnotation')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CommentAnnotation:
        """Create an instance of CommentAnnotation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in codes (list)
        _items = []
        if self.codes:
            for _item in self.codes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['codes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CommentAnnotation:
        """Create an instance of CommentAnnotation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CommentAnnotation.parse_obj(obj)

        _obj = CommentAnnotation.parse_obj({
            "id": obj.get("id"),
            "text": obj.get("text"),
            "codes": [Code.from_dict(_item) for _item in obj.get("codes")] if obj.get("codes") is not None else None,
            "instance_type": obj.get("instanceType")
        })
        return _obj


