# coding: utf-8

"""
    DDF USDM API

    A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.

    The version of the OpenAPI document: 3.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, constr, validator
from openapi_client.models.alias_code import AliasCode

class QuantityOutput(BaseModel):
    """
    QuantityOutput
    """
    id: constr(strict=True, min_length=1) = Field(...)
    value: Union[StrictFloat, StrictInt] = Field(...)
    unit: Optional[AliasCode] = None
    instance_type: StrictStr = Field(default=..., alias="instanceType")
    __properties = ["id", "value", "unit", "instanceType"]

    @validator('instance_type')
    def instance_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('Quantity',):
            raise ValueError("must be one of enum values ('Quantity')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QuantityOutput:
        """Create an instance of QuantityOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of unit
        if self.unit:
            _dict['unit'] = self.unit.to_dict()
        # set to None if unit (nullable) is None
        # and __fields_set__ contains the field
        if self.unit is None and "unit" in self.__fields_set__:
            _dict['unit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QuantityOutput:
        """Create an instance of QuantityOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QuantityOutput.parse_obj(obj)

        _obj = QuantityOutput.parse_obj({
            "id": obj.get("id"),
            "value": obj.get("value"),
            "unit": AliasCode.from_dict(obj.get("unit")) if obj.get("unit") is not None else None,
            "instance_type": obj.get("instanceType")
        })
        return _obj


