# coding: utf-8

"""
    DDF USDM API

    A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.

    The version of the OpenAPI document: 3.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr, validator
from openapi_client.models.administration_output import AdministrationOutput
from openapi_client.models.code import Code
from openapi_client.models.comment_annotation import CommentAnnotation
from openapi_client.models.quantity_output import QuantityOutput

class StudyInterventionOutput(BaseModel):
    """
    StudyInterventionOutput
    """
    id: constr(strict=True, min_length=1) = Field(...)
    name: constr(strict=True, min_length=1) = Field(...)
    label: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    role: Code = Field(...)
    type: Code = Field(...)
    minimum_response_duration: Optional[QuantityOutput] = Field(default=None, alias="minimumResponseDuration")
    codes: Optional[conlist(Code)] = None
    administrations: Optional[conlist(AdministrationOutput)] = None
    notes: Optional[conlist(CommentAnnotation)] = None
    instance_type: StrictStr = Field(default=..., alias="instanceType")
    __properties = ["id", "name", "label", "description", "role", "type", "minimumResponseDuration", "codes", "administrations", "notes", "instanceType"]

    @validator('instance_type')
    def instance_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('StudyIntervention',):
            raise ValueError("must be one of enum values ('StudyIntervention')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StudyInterventionOutput:
        """Create an instance of StudyInterventionOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of role
        if self.role:
            _dict['role'] = self.role.to_dict()
        # override the default output from pydantic by calling `to_dict()` of type
        if self.type:
            _dict['type'] = self.type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of minimum_response_duration
        if self.minimum_response_duration:
            _dict['minimumResponseDuration'] = self.minimum_response_duration.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in codes (list)
        _items = []
        if self.codes:
            for _item in self.codes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['codes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in administrations (list)
        _items = []
        if self.administrations:
            for _item in self.administrations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['administrations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in notes (list)
        _items = []
        if self.notes:
            for _item in self.notes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['notes'] = _items
        # set to None if label (nullable) is None
        # and __fields_set__ contains the field
        if self.label is None and "label" in self.__fields_set__:
            _dict['label'] = None

        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if minimum_response_duration (nullable) is None
        # and __fields_set__ contains the field
        if self.minimum_response_duration is None and "minimum_response_duration" in self.__fields_set__:
            _dict['minimumResponseDuration'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StudyInterventionOutput:
        """Create an instance of StudyInterventionOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StudyInterventionOutput.parse_obj(obj)

        _obj = StudyInterventionOutput.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "role": Code.from_dict(obj.get("role")) if obj.get("role") is not None else None,
            "type": Code.from_dict(obj.get("type")) if obj.get("type") is not None else None,
            "minimum_response_duration": QuantityOutput.from_dict(obj.get("minimumResponseDuration")) if obj.get("minimumResponseDuration") is not None else None,
            "codes": [Code.from_dict(_item) for _item in obj.get("codes")] if obj.get("codes") is not None else None,
            "administrations": [AdministrationOutput.from_dict(_item) for _item in obj.get("administrations")] if obj.get("administrations") is not None else None,
            "notes": [CommentAnnotation.from_dict(_item) for _item in obj.get("notes")] if obj.get("notes") is not None else None,
            "instance_type": obj.get("instanceType")
        })
        return _obj


