# coding: utf-8

"""
    DDF USDM API

    A simple TransCelerate Digital Data Flow (DDF) Study Definitions Repository API.

    The version of the OpenAPI document: 3.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr, validator
from openapi_client.models.parameter_map import ParameterMap

class SyntaxTemplateDictionary(BaseModel):
    """
    SyntaxTemplateDictionary
    """
    id: constr(strict=True, min_length=1) = Field(...)
    name: constr(strict=True, min_length=1) = Field(...)
    label: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    parameter_maps: conlist(ParameterMap) = Field(default=..., alias="parameterMaps")
    instance_type: StrictStr = Field(default=..., alias="instanceType")
    __properties = ["id", "name", "label", "description", "parameterMaps", "instanceType"]

    @validator('instance_type')
    def instance_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('SyntaxTemplateDictionary',):
            raise ValueError("must be one of enum values ('SyntaxTemplateDictionary')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SyntaxTemplateDictionary:
        """Create an instance of SyntaxTemplateDictionary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in parameter_maps (list)
        _items = []
        if self.parameter_maps:
            for _item in self.parameter_maps:
                if _item:
                    _items.append(_item.to_dict())
            _dict['parameterMaps'] = _items
        # set to None if label (nullable) is None
        # and __fields_set__ contains the field
        if self.label is None and "label" in self.__fields_set__:
            _dict['label'] = None

        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SyntaxTemplateDictionary:
        """Create an instance of SyntaxTemplateDictionary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SyntaxTemplateDictionary.parse_obj(obj)

        _obj = SyntaxTemplateDictionary.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "parameter_maps": [ParameterMap.from_dict(_item) for _item in obj.get("parameterMaps")] if obj.get("parameterMaps") is not None else None,
            "instance_type": obj.get("instanceType")
        })
        return _obj


